#+TITLE:CentOS 下 shadowsocks-nodejs 一键安装脚本

* 本脚本适用环境
系统支持：CentOS/Redhat/Fedora
内存要求：≥128M
=日期：2014 年 07 月 12 日=

* 关于本脚本
一键安装 Nodejs 版的 shadowsocks 最新版本，同时会安装 Nodejs 及其安装工具 npm。
备注：因为需要编译安装 Nodejs 的最新版，如果内存太小的话会安装失败，因此本人只在
最低 128MB 的 VPS 上测试过该脚本。

* 默认配置
服务器端口：8989
客户端端口：1080
密码：自己设定（如不设定，默认为 teddysun.com）

* 客户端下载
http://sourceforge.net/projects/shadowsocksgui/files/dist/

* 使用方法
使用 root 用户登录，运行以下命令：
#+BEGIN_SRC bash
wget --no-check-certificate https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-nodejs.sh
chmod +x shadowsocks-nodejs.sh
./shadowsocks-nodejs.sh 2>&1 | tee shadowsocks-nodejs.log
#+END_SRC

安装完成后，脚本提示如下：
#+BEGIN_EXAMPLE
Congratulations, shadowsocks-nodejs install completed!
Your Server IP:your_server_ip
Your Server Port:8989
Your Password:your_password
Your Local IP:127.0.0.1
Your Local Port:1080
Your Encryption Method:aes-256-cfb

Welcome to visit:https://teddysun.com/355.html
Enjoy it!
#+END_EXAMPLE

* 卸载方法
使用 root 用户登录，运行以下命令：
#+BEGIN_SRC bash
./shadowsocks-nodejs.sh uninstall
#+END_SRC

* 其他事项
客户端配置的参考链接：https://teddysun.com/339.html

安装完成后即已后台启动 shadowsocks 的服务器端 ssserver，运行：
#+BEGIN_SRC bash
ps -ef | grep ssserver | grep -v ps | grep -v grep
#+END_SRC

查看进程是否存在。
如果想要重启 ssserver 服务，按照以下步骤：

1、结束原进程。执行：
#+BEGIN_SRC bash
killall node
#+END_SRC

2、后台开启新的进程。执行：
#+BEGIN_SRC bash
nohup ssserver -c /etc/config.json > /dev/null 2>&1 &
#+END_SRC

本脚本安装完成后，会将 shadowsocks-nodejs 加入开机自启动。

最后，关于 shadowsocks-nodejs 版的配置文件（/etc/config.json）说明如下：
#+BEGIN_SRC javascript
{
    "server":"my_server_ip",
    "server_port":8989,
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"teddysun.com",
    "timeout":600,
    "method":"aes-256-cfb"
}
#+END_SRC

server：服务器 IP (IPv4/IPv6)，这也是服务端监听的 IP 地址
server_port：服务器端口
local_address：本地监听的 IP 地址
local_port：本地端端口
password：加密的密码
timeout：超时时间（秒）
method：加密方法，可选择 “bf-cfb”, “aes-256-cfb”, “des-cfb”, “rc4″, 等等。
        默认“table”是一种不安全的加密，推荐用 “aes-256-cfb”。
